name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
